name: "TODO"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "todo-to-issue"
        uses: "zackbraksa/todo-to-issue-action@master"
        with:
          AUTO_ASSIGN: true
